trigger:
  branches:
    include:
      - main

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '7.0.x'
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '**/*.sln'
    - task: VSBuild@1
      inputs:
        solution: '**/*.sln'
        msbuildArgs: '/p:Configuration=$(buildConfiguration)'
        platform: 'Any CPU'
        configuration: '$(buildConfiguration)'

- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: TestJob
    steps:
    - task: VSTest@2
      inputs:
        platform: 'Any CPU'
        configuration: '$(buildConfiguration)'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Test
  jobs:
  - job: DeployJob
    steps:
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'DotnetWebAppConnection'  # Your service connection name
        appType: 'webApp'
        appName: 'MyDotnetWebApp'                    # Your Azure Web App name
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'

schedules:
  - cron: '0 0 * * *'
    displayName: Daily Midnight Build
    branches:
      include:
        - main
    always: true

  - cron: '0 10 * * *'
    displayName: Daily Morning 10AM Build
    branches:
      include:
        - main
    always: true

  - cron: '0 12 * * 0'
    displayName: Weekly Sunday Noon Build
    branches:
      include:
        - main
    always: true