trigger:
  branches:
    include:
      - main

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    steps:
    - checkout: self
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '7.0.x'
    - task: NuGetCommand@2
      inputs:
        restoreSolution: 'DotnetProject.sln'
    - task: VSBuild@1
      inputs:
        solution:  'sriramreddy0605.DotnetProject/MyApp.csproj'
        msbuildArgs: 'sriramreddy0605.DotnetProject.sln /p:Configuration=Release
'
        platform: 'Any CPU'
        configuration: '$(buildConfiguration)'

- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: TestJob
    steps:
    - task: VSTest@2
      inputs:
        platform: 'Any CPU'
        configuration: '$(buildConfiguration)'
        publishTestResults: true

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Test
  jobs:
  - job: DeployJob
    steps:
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'DotnetWebAppConnection'
        appType: 'webApp'
        appName: 'MyDotnetWebApp'
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'

schedules:
- cron: '0 0 * * *'
  displayName: Daily Midnight Build
  branches:
    include:
      - main
  always: true

- cron: '35 4 * * *'
  displayName: Daily Morning 10:05AM IST Build
  branches:
    include:
      - main
  always: true

- cron: '0 12 * * 0'
  displayName: Weekly Sunday Noon Build
  branches:
    include:
      - main
  always: true